### PR TITLE
Fix #18: missing Gstreamer issue

### LINKED ISSUE #18: Script does not work in Arch Linux!
Hi there!

Actually, in Arch Linux, the Gstreamer directory is `/usr/lib/gstreamer-1.0` instead of `/usr/lib/x86_64-linux-gnu/gstreamer-1.0` , unlike Debian Based distributions.

So, the script fails on the non-Debian distributions due to Gstreamer not found issue.

### PR DESCRIPTION
**Pull request by namanlp**
Fixes https://github.com/linuxdeploy/linuxdeploy-plugin-gstreamer/issues/18

If the Gstreamer does not exist at `/usr/lib/$(uname -m)-linux-gnu/gstreamer-"$GSTREAMER_VERSION"`, we simply search for `/usr/lib/gstreamer-"$GSTREAMER_VERSION"` as well.

### CODE REVIEW

**Review by TheAssassin — APPROVED** [review]

File: linuxdeploy-plugin-gstreamer.sh [hunk 1]
```diff
@@ -76,8 +76,10 @@ helpers_target_dir="$APPDIR"/usr/lib/gstreamer"$GSTREAMER_VERSION"/gstreamer-"$G
 
 if [ "$GSTREAMER_PLUGINS_DIR" != "" ]; then
     plugins_dir="${GSTREAMER_PLUGINS_DIR}"
-else
+elif [ -d /usr/lib/$(uname -m)-linux-gnu/gstreamer-"$GSTREAMER_VERSION" ]; then
```
Comment (TheAssassin) [inline linuxdeploy-plugin-gstreamer.sh:79]:
```suggestion
elif [ -d /usr/lib/"$(uname -m)"-linux-gnu/gstreamer-"$GSTREAMER_VERSION" ]; then
```

**Review by TheAssassin — CHANGES_REQUESTED** [review]
